---

  hosts: webserver
  become: true
  tasks:
  - name: install Apache web server
    apt: 
      name=apache2
      state: present
    tags: apache
  - name: Instalar PHP
    apt:
      name:
      -php
      state: present

  hosts: database
  become: true
  tasks:
  - name: Instalar MySQL
    apt:
      name: mysql-server
      state: present

  - name: Copiar archivo de configuración
    copy:
      src: files/my.cnf
      dest: /etc/mysql/my.cnf
    notify:
        - Reiniciar MySQL

  - name: Crear base de datos
    mysql_db:
      name: test_db
      state: present
    notify:
        - Reiniciar MySQL

  - name: Crear usuario y otorgar privilegios
    mysql_user:
      name: user11
      password: password
      login_user: root
      login_password: password
      priv: "test_db.*:ALL"
      state: present
